// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDrbyIFnCZFvftsQDWw6BIaDIxEMOJtHM',
    appId: '1:706588275698:web:645576268d002dcc35716b',
    messagingSenderId: '706588275698',
    projectId: 'flutter-haber-uygulamasi',
    authDomain: 'flutter-haber-uygulamasi.firebaseapp.com',
    storageBucket: 'flutter-haber-uygulamasi.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy6eIjh076LItLMYogZp1a-x0cfNO_9TQ',
    appId: '1:706588275698:android:c71e139657c0aa3a35716b',
    messagingSenderId: '706588275698',
    projectId: 'flutter-haber-uygulamasi',
    storageBucket: 'flutter-haber-uygulamasi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDU7NYf6opQAa2IRjGRXuHKcD9mE4KiVBs',
    appId: '1:706588275698:ios:3fae63653a3e21d135716b',
    messagingSenderId: '706588275698',
    projectId: 'flutter-haber-uygulamasi',
    storageBucket: 'flutter-haber-uygulamasi.firebasestorage.app',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDrbyIFnCZFvftsQDWw6BIaDIxEMOJtHM',
    appId: '1:706588275698:web:8c4f8032a8b38b0c35716b',
    messagingSenderId: '706588275698',
    projectId: 'flutter-haber-uygulamasi',
    authDomain: 'flutter-haber-uygulamasi.firebaseapp.com',
    storageBucket: 'flutter-haber-uygulamasi.firebasestorage.app',
  );
}
